source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', :path=>'../sdk/'
    pod 'SDWebImage', '3.7.5'
    # release delete head
    pod 'WXDevtool', :path=>'../WXDevtool/'
#    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    # release delete tail
end

target 'WeexApp’ do
    common
end